import Observation

/// Internal protocol that exposes the observation registrar generated by `@Scriptable`.
///
/// Property wrappers (`ScriptableProperty`, `ScriptableElement`) use this
/// in their static subscripts to integrate with the Observation framework,
/// allowing SwiftUI to detect mutations.
public protocol _ScriptableObservable: AnyObject, Observable {
    var _$observationRegistrar: ObservationRegistrar { get }
}

/// Marks a class as a scriptable object, generating:
/// - `ScriptableObject` protocol conformance
/// - `Observable` conformance (observation tracking)
/// - `@MainActor` isolation
///
/// Usage:
/// ```swift
/// @Scriptable("document", code: "docu")
/// class Document {
///     @ScriptableProperty("name", code: "pnam")
///     var name: String = "Untitled"
/// }
/// ```
///
/// - Parameters:
///   - name: The SDEF-visible class name (e.g., "todo list"). Defaults to the Swift class name.
///   - code: The four-char class code (e.g., "docu"). Defaults to the first 4 characters of the class name.
///
/// Note: The class must also explicitly conform to `ScriptableObject`
/// or the generated extension will add conformance.
@attached(member, names: named(scriptableID), named(scriptableName), named(scriptingClassDescription), named(_$observationRegistrar))
@attached(extension, conformances: Observable, _ScriptableObservable)
public macro Scriptable(_ name: String? = nil, code: FourCharCode? = nil) = #externalMacro(module: "SwiftScriptingMacros", type: "ScriptableMacro")
