/// Core protocol for objects that participate in the scriptable object model.
///
/// Types conforming to this protocol can be resolved via Apple Event object specifiers
/// and manipulated through scripting commands (get, set, make, delete, etc.).
///
/// Conformance is typically generated by the `@Scriptable` macro.
@MainActor
public protocol ScriptableObject: AnyObject, Identifiable, ScriptableValue {
    /// Static metadata describing this class's scripting interface.
    static var scriptingClassDescription: ScriptingClassDescription { get }

    /// A unique, stable identifier for object resolution.
    nonisolated var scriptableID: String { get }

    /// Human-readable name for "by name" resolution (e.g., `document "Untitled"`).
    var scriptableName: String? { get }

    /// Read a property value by its four-char code.
    func scriptableValue(forProperty code: FourCharCode) -> any ScriptableValue

    /// Write a property value by its four-char code.
    func setScriptableValue(_ value: any ScriptableValue, forProperty code: FourCharCode) throws

    /// Access contained elements by their four-char class code.
    func scriptableElements(forCode code: FourCharCode) -> [any ScriptableObject]

    /// Insert an element at the given index.
    func insertScriptableElement(_ object: any ScriptableObject, forCode code: FourCharCode, at index: Int) throws

    /// Remove the element at the given index.
    func removeScriptableElement(at index: Int, forCode code: FourCharCode) throws
}

// MARK: - Default Identifiable conformance

extension ScriptableObject {
    public nonisolated var id: String { scriptableID }
}

// MARK: - ScriptableValue conformance

/// Allows ScriptableObject instances to be returned from property getters
/// (e.g. `selection` returning a reference to a todo list).
extension ScriptableObject {
    public nonisolated static var scriptingType: ScriptingType { .objectSpecifier("") }
}

// MARK: - Default Closure-Based Dispatch

extension ScriptableObject {
    public func scriptableValue(forProperty code: FourCharCode) -> any ScriptableValue {
        if let prop = Self.scriptingClassDescription.property(forCode: code), let getter = prop.getter {
            return getter(self)
        }
        return "" as any ScriptableValue
    }

    public func setScriptableValue(_ value: any ScriptableValue, forProperty code: FourCharCode) throws {
        if let prop = Self.scriptingClassDescription.property(forCode: code), let setter = prop.setter {
            try setter(self, value)
            return
        }
        throw ScriptingError.propertyNotFound(code)
    }

    public func scriptableElements(forCode code: FourCharCode) -> [any ScriptableObject] {
        if let elem = Self.scriptingClassDescription.element(forCode: code), let getter = elem.getter {
            return getter(self)
        }
        return []
    }

    public func insertScriptableElement(_ object: any ScriptableObject, forCode code: FourCharCode, at index: Int) throws {
        if let elem = Self.scriptingClassDescription.element(forCode: code), let inserter = elem.inserter {
            try inserter(self, object, index)
            return
        }
        throw ScriptingError.elementNotFound(code)
    }

    public func removeScriptableElement(at index: Int, forCode code: FourCharCode) throws {
        if let elem = Self.scriptingClassDescription.element(forCode: code), let remover = elem.remover {
            try remover(self, index)
            return
        }
        throw ScriptingError.elementNotFound(code)
    }
}

// MARK: - Scripting Errors

/// Errors that can occur during scripting operations.
public enum ScriptingError: Error, Sendable, CustomStringConvertible {
    case propertyNotFound(FourCharCode)
    case elementNotFound(FourCharCode)
    case typeMismatch(expected: Any.Type)
    case readOnlyProperty(FourCharCode)
    case indexOutOfBounds(index: Int, count: Int)
    case objectNotFound(String)
    case invalidSpecifier(String)
    case commandFailed(String)

    public var description: String {
        switch self {
        case .propertyNotFound(let code):
            return "Property not found: \(code)"
        case .elementNotFound(let code):
            return "Element not found: \(code)"
        case .typeMismatch(let expected):
            return "Type mismatch: expected \(String(describing: expected))"
        case .readOnlyProperty(let code):
            return "Property is read-only: \(code)"
        case .indexOutOfBounds(let index, let count):
            return "Index \(index) out of bounds (count: \(count))"
        case .objectNotFound(let desc):
            return "Object not found: \(desc)"
        case .invalidSpecifier(let desc):
            return "Invalid specifier: \(desc)"
        case .commandFailed(let desc):
            return "Command failed: \(desc)"
        }
    }

    /// Apple Event error code for this scripting error.
    public var aeErrorCode: Int {
        switch self {
        case .propertyNotFound: return -1728
        case .elementNotFound: return -1728
        case .typeMismatch: return -1700
        case .readOnlyProperty: return -10006
        case .indexOutOfBounds: return -1728
        case .objectNotFound: return -1728
        case .invalidSpecifier: return -1708
        case .commandFailed: return -10000
        }
    }
}
